Zimbra/packages

zimbra/osl/zimbra-osl/debian/changelog, zimbra/osl/zimbra-osl/open_source_licenses.txt, zimbra/osl/zimbra-osl/rpm/SPECS/osl.spec
Bump OpenSSL version
Tweak rsync bits for additional 3rd party license to current version.  Fix windows based formatting from old license generation system.
=> bug 103561 - Update OpenSSL version

thirdparty/nginx/nginx-1.7.1-zimbra/src/core/ngx_resolver.c, thirdparty/nginx/nginx-1.7.1-zimbra/src/core/ngx_resolver.h
As per comment # 1 in bugzilla ticket 103578, have merged
src/core/ngx_resolver.[ch] from nginx release 1.8.1. This is
to address the following:
- Invalid pointer dereference might occur during DNS server response
processing, allowing an attacker who is able to forge UDP
packets from the DNS server to cause worker process crash
(CVE-2016-0742).
- Use-after-free condition might occur during CNAME response
processing.  This problem allows an attacker who is able to trigger
name resolution to cause worker process crash, or might
have potential other impact (CVE-2016-0746).
- CNAME resolution was insufficiently limited, allowing an attacker who
is able to trigger arbitrary name resolution to cause excessive resource
consumption in worker processes (CVE-2016-0747).
After applying changes, …
=> bug 103578 - patch nginx for 3 CVEs

thirdparty/nginx/zimbra-nginx/debian/rules, thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
As it turns out, building nginx with -O2 causes our lookup
extensions to fail.  More work is needed to determing the reason for
this, but for now, compiling without -O2 enables our lookup code
to function correctly.
=> bug 103109 - Build with optimization level 0

thirdparty/openjdk-cacerts/zimbra-openjdk-cacerts/debian/changelog, thirdparty/openjdk-cacerts/zimbra-openjdk-cacerts/debian/rules, thirdparty/openjdk-cacerts/zimbra-openjdk-cacerts/debian/zimbra-openjdk-cacerts.postinst, thirdparty/openjdk-cacerts/zimbra-openjdk-cacerts/debian/zimbra-openjdk-cacerts.preinst, thirdparty/openjdk-cacerts/zimbra-openjdk-cacerts/rpm/SPECS/openjdk-cacerts.spec, thirdparty/openjdk/zimbra-openjdk/debian/changelog, thirdparty/openjdk/zimbra-openjdk/debian/rules, thirdparty/openjdk/zimbra-openjdk/rpm/SPECS/openjdk.spec
Update the openjdk and openjdk-cacerts packages to relocate the cacerts file to /opt/zimbra/common/etc/java/cacerts, and use a symlink in the openjdk package to point it.  Confirmed proper creation of symlink (openjdk) and new install location (openjdk-cacerts)
=> bug 103955 - Update packages to fix cacerts

build-order
There are two wrong package names in `build-order`. I noticed this since I use that file for my `make world` hack.
=> Fix build-order: perl-{convert,compress}-raw-{bzip2,zlib}

package-RHEL.def, package-UBUNTU.def, package-deb.def, package-rpm.def, package.def, thirdparty/perl-bit-vector/Makefile, thirdparty/perl-bit-vector/RHEL6_64.def, thirdparty/perl-date-calc/Makefile, thirdparty/perl-date-calc/RHEL6_64.def, thirdparty/perl-file-libmagic/Makefile, thirdparty/perl-file-libmagic/RHEL.def, thirdparty/perl-file-libmagic/UBUNTU.def, thirdparty/perl-socket/Makefile, thirdparty/perl-socket/RHEL6_64.def, thirdparty/perl-zmq-libzmq3/Makefile, thirdparty/perl-zmq-libzmq3/RHEL.def, thirdparty/perl-zmq-libzmq3/UBUNTU.def, zimbra/os-requirements/Makefile, zimbra/os-requirements/RHEL.def, zimbra/os-requirements/UBUNTU.def
I'm working on porting Zimbra on a not-yet supported (or not-anymore since most platforms were dropped) platform/distribution.
This patch set allows me to work on this without touching def file sand Makefiles which require adaption. It does:
* Automatically detect the correct package-DIST.def file by looking at BUILD_PLATFORM.
* Includes additional def files in the package directories if they exist. Cf. 7deff8b for an explanation.
* Ports most of the packages which have platform specifica to this format.
I didn't touch `thirdparty/openjdk` and `thirdparty/perl-extutils-constant` since the overrides there aren't relevant for my case.
The affected packages still build fine on Ubuntu 14.04 (should be tested with a RHEL6_64 as well though).
=> Extract platform specifica into separate def files

thirdparty/openjdk/zimbra-openjdk/rpm/SPECS/openjdk.spec
[root@c690 x86_64]# rpm -i zimbra-openjdk-1.8.0u92b14-1zimbra9.0b3.el6.x86_64.rpm
[root@c690 x86_64]# ls -l /opt/zimbra/common/lib/jvm/java/lib/ct.sym
-rw-r--r-- 1 root root 17726452 May 26 10:35 /opt/zimbra/common/lib/jvm/java/lib/ct.sym
=> Bug 105058 - Fix RPM build of OpenJDK to set the correct perms on ct.sym

thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_handler.c, thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_throttle_module.c, thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_throttle_module.h
This pull request is part of the work required to move all POP3/IMAP throttling out of Jetty and into nginx.  In particular, this pull requests implements separately-configurable IP-based throttling for POP3 and IMAP.
The nginx configuration directives related to IP throttling are as follows.  The first two in the list are the existing directives.  If new directives are not present, the per-protocol value to use it taken from them.
- `mail_login_ip_max`
- `mail_login_ip_ttl`
- `mail_login_ip_imap_max`
- `mail_login_ip_imap_ttl`
- `mail_login_ip_pop3_max`
- `mail_login_ip_pop3_ttl`
I have attached a test script called `mail-login-test` to Jira ticket `ZMS-48` that may be used to test the new per-protocol IP throttling feature.
Implemented Gren's suggestion with regard to log message …
=> ZMS-55 Add per-protocol (POP3/IMAP) support to ngx_mail_throttle_module

thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_handler.c, thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_throttle_module.c, thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_throttle_module.h
This adds support for *whitelisting* IPV4 or IPV6 addresses so that they will not be subject to the IMAP or POP3 throttling configuration.  The new nginx configuration directive is `mail_whitelist_ip`.  This directive may be repeated as many times as necessary.  Currently this is done in the `nginx.conf.mail` configuration file.
Ranges of IP addresses may be whitelisted via a single directive by using the appropriate [CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing) notation.  Note that when IPV6 is enabled for the cluster, you should use IPV6-formatted entries in the configuration file.  IPV6 mode is enabled when `zimbraIPMode` is set to `ipv6` or `both`.
Whitelist everything on the `10.0.2.x` subnet using IPV4 notation:
mail_whitelist_ip 10.0.2.0/24;
Whitelist …
=> ZMS-59 - ngx_mail_throttle_module zimbraThrottleWhitelist support

zimbra/core-components/Makefile, zimbra/core-components/zimbra-core-components/debian/changelog, zimbra/core-components/zimbra-core-components/debian/control, zimbra/core-components/zimbra-core-components/rpm/SPECS/core-components.spec, zimbra/mta-components/zimbra-mta-components/debian/changelog, zimbra/mta-components/zimbra-mta-components/debian/control, zimbra/mta-components/zimbra-mta-components/rpm/SPECS/mta-components.spec, zimbra/store-components/Makefile, zimbra/store-components/zimbra-store-components/debian/changelog, zimbra/store-components/zimbra-store-components/debian/control, zimbra/store-components/zimbra-store-components/rpm/SPECS/store-components.spec
Upgraded zimbra-core-components, zimbra-store-components, zimbra-mta-components to allow upgrade of MariaDB to 10.1.25.  This continues the changes done for zimbra-mariadb upgrade via commit 318df78d1.
=> BUG:107201, ZCS-412 - Upgraded MARIADB to latest (10.1.25) to fix CVE-2016-6664

thirdparty/nginx/nginx-1.7.1-zimbra/src/http/ngx_http_upstream.c
Problem
In general, Nginx chooses the initial upstream MBS (where the login page is fetched) based on the client's source IP address.  When the chosen upstream MBS is down, Nginx is supposed to switch to other MBS; it works when the zimbraMailUrl is set to the default value '/'.  But, if the zimbraMailUrl is set to other than '/', such as '/zimbra' the former default value of the 'zimbraMailUrl', the Nginx does not failover the running MBS but returns 502 error.
This bug was introduced by the Bugzilla 79621.  The bug fix description said:
```
Added a check for HTTP POST requests to terminate the connection if the upstream server is down and if the request is not a auth request.
Web client auth request are HTTP POST request with URI '/' and can also include URL prefix from 'zimbraMailURL'. …
```
=> ZCS-5790:login gets 502 when one of MBS servers is down

thirdparty/nginx/nginx-1.7.1-zimbra/src/core/ngx_zm_lookup.c, thirdparty/nginx/nginx-1.7.1-zimbra/src/core/ngx_zm_lookup.h, thirdparty/nginx/zimbra-nginx/debian/changelog, thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
**Problem:** lookup does not happen to the next server in case of https (ssl)
**Approach and Fix:**
Introduced the implementation that iterates to the next handler when one is down.
**Use cases simulating the scenario:** All Passed
1.All invalid handlers.
Configuration:
zm_lookup_handlers  https://10.15.233.175:7072/service/extension/nginx-lookup https://10.15.234.175:7072/service/extension/nginx-lookup https://10.15.235.175:7072/service/extension/nginx-lookup;
Expectation:
Fall back to IPHASH
Log output:
zmauth: an error occurs during zm lookup: no valid lookup handlers, fall back to IPHASH to get the upstream route while SSL handshaking
2.Two invalid handlers at beginning and one valid handler at last.
Configuration:
zm_lookup_handlers …
=> ZBUG-173: nginx lookup does not fail over to next server when peer store server is down or can't connect

thirdparty/nginx/nginx-1.7.1-zimbra/src/core/ngx_zm_lookup.c, thirdparty/nginx/zimbra-nginx/debian/changelog, thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec
**Problem:**
* Proxies do not failover to the next mailbox server if the mailbox server is hung.
**Approach and Fix:**
* Keep a marker on the number of retrials.
**Testing:**
* Tested it on mutiserver environment.
**Origin:**
* A highly escalated ticket from the two elite customers - PCCW and Orange.
=> Hotfix/zbug 838: Proxies do not failover to the next mailbox server if the server is hung

thirdparty/openssl/Makefile
This PR adds code to download openssl-fips source and build the same.
=> ZCS-8289: add openssl fips build target in Make file

thirdparty/openldap/zimbra-openldap/debian/changelog, thirdparty/openldap/zimbra-openldap/rpm/SPECS/openldap.spec, zimbra/ldap-components/zimbra-ldap-components/debian/changelog, zimbra/ldap-components/zimbra-ldap-components/debian/control, zimbra/ldap-components/zimbra-ldap-components/rpm/SPECS/ldap-components.spec
NG-Backup is stopping because it cannot read files that have the wrong permissions.
Getting below warnings from backup notification. 
Warnings:
- File /opt/zimbra/common/etc/openldap/slapd.conf is not readable
- File /opt/zimbra/common/etc/openldap/slapd.conf.default is not readable
- File /opt/zimbra/common/etc/openldap/slapd.ldif is not readable
- File /opt/zimbra/common/etc/openldap/slapd.ldif.default is not readable
=> ZBUG-1441 : Default openldap configuration files with incorrect permissions

thirdparty/nginx/nginx-1.7.1-zimbra/src/mail/ngx_mail_proxy_module.c, thirdparty/openssl/zimbra-openssl/debian/rules, thirdparty/openssl/zimbra-openssl/rpm/SPECS/openssl.spec
The current nginx code alterations introduce a memory leak concerning the tearing down of SSL connections from the proxy to the upstream mailbox servers in the case of IMAP/POP3 connections.
The SSL data structures in memory related to the upstream connections are not freed when the upstream connection is brought down leading to a memory leak which grows over time in the worker processes.
The fix is to address that bit in the connection closing process, code which was already there in the code path used for successfully established connections to the upstream server but not for connections failing because of wrong credentials or other situations.
Also added is an additional compilation switch for the OpenSSL compilation which disables the freelist buffers, a concept introduced to mitigate …
=> Nginx memory leak fix

thirdparty/nginx/nginx-1.19.0-zimbra/src/mail/ngx_mail_proxy_module.c
Relates to https://github.com/Zimbra/packages/pull/96
**Issue:**
- Memory leak concerning the tearing down of SSL connections from the proxy to the upstream mailbox servers in the case of IMAP/POP3 connections.
**Testing:**
- Tested by QA.
=> ZBUG-2098: Fixes memory leak due to upstream IMAP/POP3 ssl connections

thirdparty/nginx/nginx-1.19.0-zimbra/src/mail/ngx_mail_handler.c
**Issues solved (Telnet reported):**
Issue reported by telnet - malloc crash when throttle increase. When throttle count increases by limit, it can lead to malloc crash.
**Other crash solved:**
Dying worker processes, core dump even without the allow < limit
2021/05/07 16:14:17 [debug] 10673#0: ngx_mail_throttle_ip_success_handler: login_ip_max=10, mail_login_ip_max=10, mail_login_ip_imap_max=0, mail_login_ip_pop3_max=0
2021/05/07 16:14:17 [info] 10673#0: ip throttle:[127.0.0.1] allow [count:7, limit:10]
2021/05/07 16:14:17 [notice] 10672#0: signal 17 (SIGCHLD) received from 10673
2021/05/07 16:14:17 [alert] 10672#0: worker process 10673 exited on signal 11 (core dumped)
**Other issue solved:**
Additional throttling call and counter increase (functionally wrong).
In very slow systems, it …
=> ZBUG-2125: Malloc crash while throttling

thirdparty/unbound/zimbra-unbound/debian/changelog, thirdparty/unbound/zimbra-unbound/debian/zimbra-unbound.postinst, thirdparty/unbound/zimbra-unbound/rpm/SPECS/unbound.spec
**Problem :**  dnscache service does not support DNSSEC validation
**Fix :** This issue is due to anchor key file (/opt/zimbra/conf/root.key) is not present, to fix this need to generate anchor key file and add anchor key file path in /opt/zimbra/conf/unbound.conf.in
**Refer:**  Check the man page of "unbound-anchor" to get more details about the anchor key.
less  /opt/zimbra/common/share/man/man8/unbound-anchor.8
Related PR: https://github.com/Zimbra/zm-mailbox/pull/1251
=> ZBUG-2723 : Generate anchor key required for DNSSEC

thirdparty/nginx/zimbra-nginx/debian/changelog, thirdparty/nginx/zimbra-nginx/rpm/SPECS/nginx.spec, zimbra/proxy-components/zimbra-proxy-components/debian/changelog, zimbra/proxy-components/zimbra-proxy-components/debian/control, zimbra/proxy-components/zimbra-proxy-components/rpm/SPECS/proxy-components.spec
Updated proxy-components to 1.0.10 as part of nginx changes for ZBUG-2738
Updated zimbra-nginx  changelog as part of nginx changes for ZBUG-2738
=> ZBUG-2738 : Updated proxy-components to 1.0.10 as part of nginx changes for ZBUG-2738

thirdparty/unbound/zimbra-unbound/debian/changelog, thirdparty/unbound/zimbra-unbound/debian/zimbra-unbound.postinst, thirdparty/unbound/zimbra-unbound/rpm/SPECS/unbound.spec, zimbra/dnscache-components/zimbra-dnscache-components/debian/changelog, zimbra/dnscache-components/zimbra-dnscache-components/debian/control, zimbra/dnscache-components/zimbra-dnscache-components/rpm/SPECS/dnscache-components.spec
unbound post install script not able to generate anchor key in /opt/zimbra/conf because at the time of unbound pacakge installation /opt/zimbra/conf directory not exist. We can remove generate anchor key from post install script. We already handling this in zmdnscachectl https://github.com/Zimbra/zm-core-utils/blob/develop/src/bin/zmdnscachectl#L74
=> ZCS-11941 : Don't generate anchor key from unbound post install script

thirdparty/amavisd/patches/zbug-1457.patch, thirdparty/amavisd/zimbra-amavisd/debian/changelog, thirdparty/amavisd/zimbra-amavisd/debian/patches/series, thirdparty/amavisd/zimbra-amavisd/rpm/SPECS/amavisd.spec, zimbra/mta-components/zimbra-mta-components/debian/changelog, zimbra/mta-components/zimbra-mta-components/debian/control, zimbra/mta-components/zimbra-mta-components/rpm/SPECS/mta-components.spec
**Problem :** 
$ zmamavisdctl restart
Stopping amavisd... done.
Stopping amavisd-mc... done.
Starting amavisd-mc...done.
Starting amavisd...Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/ ( { <-- HERE } (?: / \* )? | \* ) / at (eval 100) line 784, <DATA> line 755.
done.
=> ZBUG-1457 : Fix regex error for amavisd restart

zimbra/core-components/zimbra-core-components/debian/changelog, zimbra/core-components/zimbra-core-components/debian/control, zimbra/core-components/zimbra-core-components/rpm/SPECS/core-components.spec, zimbra/ldap-components/zimbra-ldap-components/debian/changelog, zimbra/ldap-components/zimbra-ldap-components/debian/control, zimbra/ldap-components/zimbra-ldap-components/rpm/SPECS/ldap-components.spec, zimbra/os-requirements/RHEL.def, zimbra/os-requirements/UBUNTU.def, zimbra/os-requirements/zimbra-os-requirements/debian/changelog, zimbra/os-requirements/zimbra-os-requirements/rpm/SPECS/os-requirements.spec
**Problem:**
zimbra-os-requirements rpm package doesn't have dependency pax but debian package has dependency on pax. So add pax,spax in os-requirements for RHEL/CentOS/Oracle/Rocky Linux
```
coreutils
expat
file
gmp
libaio
libidn
libstdc++
pcre
perl
perl-core
sudo
sysstat
unzip
zimbra-base
perl-Socket6
nc
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
coreutils
expat
file
gmp
libaio
libidn
libstdc++
pcre
perl
perl-core
sudo
sysstat
unzip
zimbra-base
perl-Socket6
nmap-ncat
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadIsXz) <= 5.2-1
coreutils
expat
file
gmp
libaio
libidn
libstdc++
pcre
perl
perl-Socket6
perl-core
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= …
```
=> ZBUG-3017: added pax,spax in os-requirements for RHEL/CentOS/Oracle/Rocky Linux

thirdparty/httpd/zimbra-httpd/debian/changelog, thirdparty/httpd/zimbra-httpd/debian/rules, thirdparty/httpd/zimbra-httpd/rpm/SPECS/httpd.spec, zimbra/apache-components/zimbra-apache-components/debian/changelog, zimbra/apache-components/zimbra-apache-components/debian/control, zimbra/apache-components/zimbra-apache-components/rpm/SPECS/apache-components.spec, zimbra/spell-components/zimbra-spell-components/debian/changelog, zimbra/spell-components/zimbra-spell-components/debian/control, zimbra/spell-components/zimbra-spell-components/rpm/SPECS/spell-components.spec
**Problem:** 
Apache is pointing to pcre2 at compilation time instead of pointing to pcre. This is happening when pcre, pcre2 are installed on build server. Apache was compiled with pcre2 but apache binary not able to find pcre2 library on installation server and this leads to apache start failed.
**Fix:**
Apache should point to pcre at compilation time.
=> ZBUG-3126 : Compile apache with pcre
